# Generated by Django 4.1.6 on 2023-02-09 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personal_site", "0006_category_alter_article_image_women_cat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="women",
            options={
                "ordering": ["time_create", "title"],
                "verbose_name": "Известные женщины",
                "verbose_name_plural": "Известные женщины",
            },
        ),
    ]
