# Generated by Django 4.1.6 on 2023-02-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal_site", "0009_alter_women_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=255, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
