# Generated by Django 4.1.6 on 2023-02-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("personal_site", "0010_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="article_images/",
                verbose_name="Главное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="personal_site.articletags", verbose_name="Тэги"
            ),
        ),
        migrations.CreateModel(
            name="ArticleImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="article_images")),
                ("default", models.BooleanField(verbose_name="Титульное")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="personal_site.article",
                    ),
                ),
            ],
        ),
    ]
