# Generated by Django 4.1.6 on 2023-02-27 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personal_site", "0013_alter_article_tags"),
        ("personal_site", "0013_women_user_alter_article_tags"),
    ]

    operations = []
