# Generated by Django 4.1.6 on 2023-02-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_site", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("archived", models.BooleanField(verbose_name="Архив")),
            ],
            options={
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(max_length=80, null=True, verbose_name="Путь URL"),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                to="personal_site.articletags", verbose_name="Тэги"
            ),
        ),
    ]
