# Generated by Django 4.1.6 on 2023-02-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, verbose_name='URL-путь'),
        ),
    ]
