# Generated by Django 4.1.6 on 2023-02-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0002_article_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('BL', 'Blog post'), ('PR', 'Project post')], default='BL', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=80, null=True, verbose_name='URL-путь'),
        ),
    ]
