# Generated by Django 4.1.6 on 2023-02-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0002_articletags_alter_article_slug_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='publication_date',
        ),
    ]
