# Generated by Django 4.1.6 on 2023-02-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0004_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
