# Generated by Django 4.1.6 on 2023-02-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal_site", "0011_alter_article_image_alter_article_tags_articleimages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="image",
        ),
        migrations.AddField(
            model_name="articleimages",
            name="caption",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Подпись"
            ),
        ),
        migrations.AlterField(
            model_name="articleimages",
            name="default",
            field=models.BooleanField(verbose_name="Титульное изображение"),
        ),
        migrations.AlterField(
            model_name="articleimages",
            name="image",
            field=models.ImageField(
                upload_to="article_images", verbose_name="Изображение"
            ),
        ),
    ]
