# Generated by Django 4.1.6 on 2023-02-27 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("personal_site", "0012_remove_article_image_articleimages_caption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="women",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="tags",
                to="personal_site.articletags",
                verbose_name="Тэги",
            ),
        ),
    ]
