# Generated by Django 4.1.6 on 2023-03-07 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personal_site", "0014_merge_20230227_1537"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="women",
            name="cat",
        ),
        migrations.RemoveField(
            model_name="women",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Women",
        ),
    ]
