# Generated by Django 4.1.6 on 2023-04-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal_site", "0015_remove_women_cat_remove_women_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="access_by_link",
            field=models.BooleanField(default=False, verbose_name="Доступ по ссылке"),
        ),
    ]
